apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: kustomize-
namespace: pokespace

resources:
  - namespace.yaml
  - config-map.yaml
  - pokeapi-deployment.yaml
  - pokeapi-svc.yaml
  - /Pikachu/kustomization.yaml
