apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeapi
  namespace: pokespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokeapi
  template:
    metadata:
      labels:
        app: pokeapi
    spec:
      containers:
        - name: pokeapi
          image: pokeapi:0.1
          ports:
            - containerPort: 3000
            
