apiVersion: v1
kind: Service
metadata:
  name: pokeapi-svc
  namespace: pokespace # Ajout explicite du namespace (option 1)
spec:
  selector:
    app: pokeapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
