apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeapi
  namespace: pokespace # Ajout explicite du namespace (option 1)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokeapi
  template:
    metadata:
      labels:
        app: pokeapi
    spec:
      containers:
        - name: pokeapi
          image: pokeapi:latest
          ports:
            - containerPort: 3000
            
