apiVersion: apps/v1
kind: Deployment
metadata:
  name: pikachu
  labels:
    app: pokeapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokeapi
  template:
    metadata:
      labels:
        app: pokeapi
    spec:
      containers:
        - name: pikachu
          image: pokeapi:0.1
          ports:
            - containerPort: 3000
            
